### ISSUE TITLE
Can't stop solid infill "ensure vertical shell thickness"

### ISSUE THREAD

**Issue by haleypearse** [prusa3d/PrusaSlicer-settings#61] opened 2019-01-27 19:45 UTC
Adding top and bottom layers erroneously adds solid infill. It's as if "ensure vertical shell thickness" is enabled when it isn't. Paradoxically it's not so bad with it enabled. To avoid using way more plastic I end up printing things with only a single top and bottom layer. 

Correct: Slic3r 1.2.9:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/10296672/51805876-b955fd00-2227-11e9-922c-def48ccec9c4.png">

Issue: slic3r PE 1.41.1-rc+:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/10296672/51805881-c70b8280-2227-11e9-9b29-b6a813d99aa5.png">

with "ensure vertical shell thickness" enabled:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/10296672/51805934-76e0f000-2228-11e9-93c1-88ca3e510ae8.png">

**Comment by rtyr** [comment] 2020-04-05 11:07
Duplicate of https://github.com/prusa3d/PrusaSlicer/issues/668, https://github.com/prusa3d/PrusaSlicer/issues/3744. Also it was created in the wrong repository. Closing.

**Closed by rtyr** 2020-04-05 11:07 UTC
