### ISSUE TITLE
[bug] Can't add new filaments in multi material mode

### ISSUE THREAD

**Issue by quasipedia** [prusa3d/PrusaSlicer-settings#101] opened 2020-07-18 23:15 UTC
### Version
2.2.0 (PrusaSlicer-2.2.0+linux-x64-202003211856)

### Operating system type + version
Fedora 32 (64 bit)

### 3D printer brand / version + firmware version (if known)
Original Prusa i3 MK3S with MMU2S
(Firmware updated to the latest available version to date)

### Behavior
* I'm trying to print in multi material using FLEX, But Prusa Slicer won't allow me to select the FLEX filament (won't even display it in the menu)
* Load the object
* Set the printer to `Original Prusa i3 MK3S MMU2S` in the right bar (dropdown button)
* Press any extruder dropdown button and notice as the only options given are Generic (ABS, PETG, PLA), Prusament (ASA, PETG, PLA) and Verbatim (BVOH).
* Select `------------ Add/Remove filaments -------`
* Try to activate the checkbox for the flex filament (in my case it was already active as I used already the filament in `Original Prusa i3 MK3S MMU2S Single` mode, but I tried to activate `Generic FLEX` too, and the result does not change).
* Press any extruder dropdown and the _Expected Results_ would be to have FLEX listed as an option, while the _Actual Results_ is having the menu identical to before (I also tried to close and reopen the slicer, to no avail)

![image](https://user-images.githubusercontent.com/309045/87863591-c8b99080-c95c-11ea-9dc1-5df4b601e4cd.png)

![image](https://user-images.githubusercontent.com/309045/87863610-04545a80-c95d-11ea-94e3-d0c8d451ee25.png)

_Is this a new feature request?_ No! :)

**Comment by rtyr** [comment] 2020-07-19 07:10
Duplicate of https://github.com/prusa3d/PrusaSlicer/issues/4007 and https://github.com/prusa3d/PrusaSlicer-settings/issues/97.

Intended behavior, flex filament is available only for single mode at the moment. Closing.

**Closed by rtyr** 2020-07-19 07:10 UTC
