### ISSUE TITLE
Default MMU2s Filament settings 

### ISSUE THREAD

**Issue by Larswa** [prusa3d/PrusaSlicer-settings#151] opened 2022-02-22 11:10 UTC
### Version
2.4.0

### Operating system type + version
Windows

### 3D printer brand / version + firmware version (if known)
Mk3S with MMU2S

### Behavior
**Default settings for Toolchange Parameters are REALLY bad, consistently leading to failed filament changes and loss of hair due to pulling of same and broken windows due to printers being thrown about.** 

**Could you please change the defaults?**

Background:

Having spent the weekend cursing at my newly setup MMU2, and tuning the hardware and sensors to perfection, and still having failed filament changes due to the tips consistently being too large on retraction to the MMU2, these changes to the default has worked wonders.  Before:  Failing on almost every filament retraction.   After:  Halfway through a 500 filament change print job with no failures.

This thread has listed settings that worked wonders for me, and for the sake of new MMU2 users, please update the defaults to something similar to what I got from the thread.

https://forum.prusaprinters.org/forum/original-prusa-i3-mmu2s-mmu2-general-discussion-announcements-and-releases/mmu2s-filament-tips-on-unload/paged/6/#post-584344

I made the follwowing changes:
Filament Settings > Advanced > Toolchange parameters with single extruder MM printers:
Unloading speed at the start: 140mm/s 
Unloading speed: 90mm/s 
(Increased cooling moves/ramming)
Number of cooling moves: 3 
Speed of the first cooling move: 20mm/s
Speed of the last cooling move: 10 mm/s
Ramming parameters: Total ramming time(s): 4.50

I just copied this without testing other values, and I bet that Prusa Research could probably refine this. But it works for me on a number of different PLA and PETG brands. Have not tried with other filaments.

_Is this a new feature request?_
No

**Comment by rtyr** [comment] 2022-03-25 19:46
> Default settings for Toolchange Parameters are REALLY bad, consistently leading to failed filament changes and loss of hair due to pulling of same and broken windows due to printers being thrown about.

We tested MMU very extensively, as you can read in this article https://blog.prusaprinters.org/original-prusa-i3-mk3s-and-mmu2s-release-sl1-and-powder-coated-sheets-update_29599/#2. Lot of issues can be caused by improper assembly, wet filament, etc.. Various filaments may need additional tweaking/experimenting. PETG is quite hygroscopic, so drying it may significantly increase the reliability.

> Unloading speed at the start: 140mm/s

Maximum speed is limited to 120mm/s by printer FW. Even without it, 140mm/s would be likely not reached with default retract acceleration. So if you changed for example 120 to 140 in PETG profile, the result was still 120. This speed is used for the first 15mm of filament retract (MK3S MMU2S).

> Unloading speed: 90mm/s

Moving fast with semi-molten filament tip may deform it.

> (Increased cooling moves/ramming)
> Number of cooling moves: 3
> Speed of the first cooling move: 20mm/s
> Speed of the last cooling move: 10 mm/s

Such setting will cool the filament tip for the shorter time, than default (one much slower cooling move). We used faster cooling moves initially with MMU1. Later our tests showed better results with slow/carefull cooling moves. The results may vary with different filaments of course.

> Ramming parameters: Total ramming time(s): 4.50

Total ramming time is not enough information without rest of the ramming sequence (which is different for each filament and filament type).

If you have custom profile for some particular filament, which is not currently included for MMU2, please share your profile (for example just project 3MF file) and information about that filament (brand/type). We can then test it on larger amount of printers and possibly add such profile. Closing.

**Closed by rtyr** 2022-03-25 19:46 UTC
