### ISSUE TITLE
Polymaker Polyfle TPU95

### ISSUE THREAD

**Issue by PeterWH56** [prusa3d/PrusaSlicer-settings#204] opened 2023-08-09 02:04 UTC
**Is your feature request related to a problem? Please describe.**
There is no profile for Polymaker Polyflex TPU95 in Pruser Slicer 2.6.0 for the Prusa Mk4 printer. 

**Describe the solution you'd like**
Please add Polyflex TPU95 as an available filament option.

**Describe how it would work**

**Describe alternatives you've considered**

**Additional context**

**Comment by rtyr** [comment] 2023-08-09 22:00
I am closing this as a duplicate of https://github.com/prusa3d/PrusaSlicer-settings/issues/159.

**Closed by rtyr** 2023-08-09 22:00 UTC
