### ISSUE TITLE
Prussia slicer version 2.0 support enforcer placement

### ISSUE THREAD

**Issue by bman2000** [prusa3d/PrusaSlicer-settings#72] opened 2019-06-05 12:02 UTC
Placement of enforcer is very finicky.
Moving enforcer, to position can be diificult when rotating the model as small enforcer movements van drastically kick enforcer away from model.

**Comment by rtyr** [comment] 2019-09-17 09:31
I believe this issue should be posted at https://github.com/prusa3d/PrusaSlicer. Please move it there, if the problem is still present in the latest PrusaSlicer 2.1.0.

**Comment by bman2000** [comment] 2019-09-18 09:11
This is still an issue on the newly released version.

Unfortunately I do not know how to move the issue as requested.

**Comment by rtyr** [comment] 2020-04-05 10:48
Closing here. Feel free to reopen issue at https://github.com/prusa3d/PrusaSlicer.

**Closed by rtyr** 2020-04-05 10:48 UTC
