### ISSUE TITLE
Feature request: adding profiles for 3DMaterials resin on prusa sl1 and sl1s

### ISSUE THREAD

**Issue by CanineTunic** [prusa3d/PrusaSlicer-settings#141] opened 2021-10-05 17:32 UTC
I would like to suggest that there be a profile for a resin called SuperFast made by 3DMaterials be added to PrusaSlicer. It is a unique resin that has an exposure time of 3.5/30 seconds on the Prusa SL1 and I think this would be nice to be a profile built in to PrusaSlicer by default.

**Comment by rtyr** [comment] 2021-10-05 18:45
Duplicate of https://github.com/prusa3d/PrusaSlicer-settings/pull/140. I already informed colleague who maintains resin profiles. Closing.

**Closed by rtyr** 2021-10-05 18:45 UTC
