### ISSUE TITLE
start gcode uses G21 command - which is not implemented on Prusa firmware

### ISSUE THREAD

**Issue by geeksville** [prusa3d/PrusaSlicer-settings#85] opened 2019-12-26 22:59 UTC
MK3S
3.8.1

MMU2S
1.0.6

Describe the bug
This is a minor issue but I thought I'd mention it because it causes an error message to appear in the logs.

While investigating https://github.com/prusa3d/Prusa-Firmware/issues/2388 I noticed the following error message on the serial stream from my MK3 during the start of print gcode:

```
2019-12-26 20:35:47,995 - Send: N23 G21*43
2019-12-26 20:35:48,004 - Recv: Unknown G code: $23 G21
2019-12-26 20:35:48,006 - Recv: ok
```

I think this inadvertently revealed a minor issue:

* I checked the PrusaFirmware for 3.8.1 and found out that this message was triggered because the prusa firmware does not implement the G21 command.  Which is fine, but users might be confused about this error message.  I don't know if you added this to your start gcode because it was needed for an older version of the prusa firmware but thought I'd mention it.

(The dollar sign is harmless, it is an artifact of how cmdqueue.cpp hides the N commands from the rest of marlin)

**Comment by rtyr** [comment] 2019-12-26 23:25
Duplicate of https://github.com/prusa3d/PrusaSlicer/issues/3192. G21 command is not included in the latest settings bundle, but it is added to the gcode anyway by the PrusaSlicer. I believe it is ok from PS perspective, because we are using Marlin gcode flavor and G21 command is supported by Marlin. Closing here.

**Closed by rtyr** 2019-12-26 23:25 UTC
