### ISSUE TITLE
support z contact not working correctly

### ISSUE THREAD

**Issue by Charl3s3n** [prusa3d/PrusaSlicer-settings#25] opened 2017-11-27 03:39 UTC
With a single noozle the z contact joust work for the predefinied values 0 or 0.2, but if i change this value the sliced model keeps identical if the value is lower than 0.2 and greater than 0, this opction works perfectly if the value is avobe the 0.2, when it is set to 0.2 there is a gap between the final support layer and the first objet layer about 7 layers, my layers are set to .15 so there is not a .2 z distance

**Comment by rtyr** [comment] 2020-04-05 10:55
It should be placed at prusa3d/PrusaSlicer, but we can close it anyway, since it is a duplicate of https://github.com/prusa3d/PrusaSlicer/issues/102, https://github.com/prusa3d/PrusaSlicer/issues/2766, https://github.com/prusa3d/PrusaSlicer/issues/926, https://github.com/prusa3d/PrusaSlicer/issues/198. Closing.

**Closed by rtyr** 2020-04-05 10:55 UTC
